### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by globalise1** [cloudfoundry-community/cf-meteor-buildpack#16]
I successfully uploaded an app to IBM Bluemix a couple of months ago, but now I can't push either my own app, nor the leaderboard example to Bluemix using the instructions in the documentation. Does anyone else have a problem doing so?

Thanks

**Comment by sungwoncho** [comment]
I recently used this buildpack to deploy Meteor 1.2 and 1.1.0.2 to Bluemix. What Meteor release is your app using?

**Comment by ghost** [comment]
Recently tried with 1.2.1 and it works fine. With 1.3 it doesn't work yet as it is still in beta and the script is downloading the latest stable version of Meteor.

**Comment by globalise1** [comment]
Yes, got it working in 1.2.1, but now broken due to 1.3
